// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/Card.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Markdown: typeof import('./src/components/Editior/markdown.vue')['default']
    MyButton: typeof import('./src/components/MyButton.bak/MyButton.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavBarUser: typeof import('./src/components/NavBarUser.vue')['default']
  }
}

export { }
